/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider, Wallet, AbstractAddress } from "fuels";
import { Interface, Contract } from "fuels";
import type {
  NftMarketplaceAbi,
  NftMarketplaceAbiInterface,
} from "../NftMarketplaceAbi";
const _abi = [
  {
    type: "function",
    name: "item_count",
    inputs: [],
    outputs: [
      {
        type: "u64",
        name: "",
      },
    ],
  },
  {
    type: "function",
    name: "items",
    inputs: [
      {
        type: "u64",
        name: "id",
      },
    ],
    outputs: [
      {
        type: "struct Item",
        name: "",
        components: [
          {
            type: "u64",
            name: "item_id",
          },
          {
            type: "struct ContractId",
            name: "contract_Id",
            components: [
              {
                type: "b256",
                name: "value",
              },
            ],
          },
          {
            type: "u64",
            name: "token_id",
          },
          {
            type: "u64",
            name: "price",
          },
          {
            type: "struct Address",
            name: "seller",
            components: [
              {
                type: "b256",
                name: "value",
              },
            ],
          },
          {
            type: "bool",
            name: "sold",
          },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "make_item",
    inputs: [
      {
        type: "struct ContractId",
        name: "contract_Id",
        components: [
          {
            type: "b256",
            name: "value",
          },
        ],
      },
      {
        type: "u64",
        name: "token_id",
      },
      {
        type: "u64",
        name: "price",
      },
    ],
    outputs: [
      {
        type: "()",
        name: "",
        components: [],
      },
    ],
  },
  {
    type: "function",
    name: "purchase_item",
    inputs: [
      {
        type: "u64",
        name: "item_id",
      },
    ],
    outputs: [
      {
        type: "()",
        name: "",
        components: [],
      },
    ],
  },
];

export class NftMarketplaceAbi__factory {
  static readonly abi = _abi;
  static createInterface(): NftMarketplaceAbiInterface {
    return new Interface(_abi) as unknown as NftMarketplaceAbiInterface;
  }
  static connect(
    id: string | AbstractAddress,
    walletOrProvider: Wallet | Provider
  ): NftMarketplaceAbi {
    return new Contract(
      id,
      _abi,
      walletOrProvider
    ) as unknown as NftMarketplaceAbi;
  }
}
