/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { NftMarketplaceAbi } from "./NftMarketplaceAbi";

export { NftMarketplaceAbi__factory } from "./factories/NftMarketplaceAbi__factory";
